# Generated by Django 3.2.10 on 2021-12-29 23:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='estimates_remaining',
        ),
    ]
