# Generated by Django 3.2.3 on 2021-09-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0002_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='estimates_remaining',
            field=models.IntegerField(default=0),
        ),
    ]
