# Generated by Django 3.2.3 on 2021-09-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0004_lineitems_purchaseorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='request_id',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='session_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19),
        ),
    ]
