# Generated by Django 3.2.3 on 2021-09-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0006_rename_lineitems_lineitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='line_item_id',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
