# Generated by Django 3.2.3 on 2021-09-24 05:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0008_alter_purchaseorder_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_id', models.CharField(max_length=200)),
                ('price_description', models.CharField(max_length=200)),
            ],
        ),
    ]
