# Generated by Django 4.0.2 on 2022-03-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('articles', '0003_article_image_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
