# Generated by Django 4.0.2 on 2022-03-28 01:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('articles', '0004_article_visible'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(fields=('slug',), name='uniqueSlugArticle'),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(fields=('title',), name='uniqueTitleArticle'),
        ),
    ]
