# Generated by Django 4.0.2 on 2022-03-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('articles', '0005_article_uniqueslugarticle_article_uniquetitlearticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_location',
            field=models.CharField(default='default', max_length=255),
        ),
    ]
