# Generated by Django 4.0.2 on 2022-04-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('articles', '0006_alter_article_image_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_location',
            field=models.ImageField(upload_to='article'),
        ),
    ]
