# Generated by Django 4.0.2 on 2022-04-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('articles', '0007_alter_article_image_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_style', models.CharField(max_length=255)),
                ('image_location', models.ImageField(upload_to='article')),
            ],
        ),
    ]
