# Generated by Django 4.0.2 on 2022-04-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('articles', '0008_articleimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='images',
            field=models.ManyToManyField(to='articles.ArticleImages'),
        ),
    ]
