# Generated by Django 4.0.2 on 2022-04-04 10:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('articles', '0009_article_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleImages',
            new_name='ArticleImage',
        ),
    ]
