# Generated by Django 4.0.2 on 2022-04-05 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('articles', '0010_rename_articleimages_articleimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articleimage',
            old_name='image_style',
            new_name='image_position',
        ),
        migrations.RemoveField(
            model_name='article',
            name='images',
        ),
        migrations.AddField(
            model_name='articleimage',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='articles.article'),
            preserve_default=False,
        ),
    ]
