# Generated by Django 4.0.2 on 2022-04-05 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('articles', '0011_rename_image_style_articleimage_image_position_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleImagePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='image_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='articles.articleimageposition'),
        ),
    ]
