# Generated by Django 4.0.2 on 2022-04-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('articles', '0012_articleimageposition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleimage',
            name='image_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
