# Generated by Django 4.0.2 on 2022-04-06 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('articles', '0014_remove_article_content_remove_articleimage_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleimage',
            name='paragraph',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE,
                                    to='articles.articleparagraph'),
            preserve_default=False,
        ),
    ]
