# Generated by Django 4.0.2 on 2022-04-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('articles', '0016_remove_articleparagraph_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
