# Generated by Django 4.0.2 on 2022-04-10 18:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('articles', '0017_article_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleimage',
            name='image_description',
        ),
    ]
