# Generated by Django 3.2.9 on 2021-12-15 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_type', models.CharField(default='', max_length=100)),
                ('long_name', models.CharField(default='', max_length=100)),
                ('internal_bool', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='', max_length=100)),
                ('active_bool', models.BooleanField(default=False)),
                ('ep_bool', models.BooleanField(default=False)),
                ('pct_ro_bool', models.BooleanField(default=False)),
                ('pct_accept_bool', models.BooleanField(default=False)),
                ('currency_name', models.CharField(default='', max_length=5)),
                ('long_name', models.CharField(default='', max_length=100)),
                ('color', models.CharField(default='', max_length=20)),
                ('available_appl_types', models.ManyToManyField(to='characteristics.ApplType')),
            ],
        ),
        migrations.CreateModel(
            name='DocFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EPValidationTranslationRequired',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('words_per_page', models.IntegerField()),
                ('ep_official_language_bool', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OfficeActionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oa_bool', models.BooleanField()),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TranslationImplementedPseudoEnum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OANumPerCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oa_num', models.IntegerField(default=2)),
                ('country',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristics.country')),
            ],
        ),
        migrations.CreateModel(
            name='LanguageCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default', models.BooleanField(default=False)),
                ('appl_type',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristics.appltype')),
                ('country',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristics.country')),
                ('language',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristics.language')),
            ],
        ),
        migrations.CreateModel(
            name='EntitySize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_size', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('default_bool', models.BooleanField(default=False)),
                ('country',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristics.country')),
            ],
        ),
        migrations.CreateModel(
            name='DocFormatCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default', models.BooleanField(default=False)),
                ('appl_type',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristics.appltype')),
                ('country',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristics.country')),
                ('doc_format',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristics.docformat')),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='available_doc_formats',
            field=models.ManyToManyField(related_name='available_doc_formats',
                                         through='characteristics.DocFormatCountry', to='characteristics.DocFormat'),
        ),
        migrations.AddField(
            model_name='country',
            name='available_languages',
            field=models.ManyToManyField(related_name='available_languages', through='characteristics.LanguageCountry',
                                         to='characteristics.Language'),
        ),
        migrations.AddField(
            model_name='country',
            name='ep_validation_translation_required',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='characteristics.epvalidationtranslationrequired'),
        ),
        migrations.AddField(
            model_name='country',
            name='isa_countries',
            field=models.ManyToManyField(related_name='_characteristics_country_isa_countries_+',
                                         to='characteristics.Country'),
        ),
        migrations.AddConstraint(
            model_name='appltype',
            constraint=models.UniqueConstraint(fields=('application_type',), name='applicationTypeUniqueConstraint'),
        ),
        migrations.AddConstraint(
            model_name='oanumpercountry',
            constraint=models.UniqueConstraint(fields=('country',), name='countryOANumUniqueConstraint'),
        ),
        migrations.AddConstraint(
            model_name='languagecountry',
            constraint=models.UniqueConstraint(fields=('language', 'country', 'appl_type'),
                                               name='LanguageCountryUniqueConstraint'),
        ),
        migrations.AddConstraint(
            model_name='languagecountry',
            constraint=models.UniqueConstraint(condition=models.Q(('default', True)), fields=('language', 'appl_type'),
                                               name='LanguageCountryUniqueDefaultConstraint'),
        ),
        migrations.AddConstraint(
            model_name='entitysize',
            constraint=models.UniqueConstraint(fields=('entity_size', 'country'),
                                               name='entitySizeCountryUniqueConstraint'),
        ),
        migrations.AddConstraint(
            model_name='entitysize',
            constraint=models.UniqueConstraint(condition=models.Q(('default_bool', True)), fields=('country',),
                                               name='DefaultEntitySizeCountryUniqueConstraint'),
        ),
        migrations.AddConstraint(
            model_name='docformatcountry',
            constraint=models.UniqueConstraint(fields=('doc_format', 'country', 'appl_type'),
                                               name='DocFormatCountryUniqueConstraint'),
        ),
        migrations.AddConstraint(
            model_name='docformatcountry',
            constraint=models.UniqueConstraint(condition=models.Q(('default', True)), fields=('country', 'appl_type'),
                                               name='DocFormatCountryUniqueDefaultConstraint'),
        ),
        migrations.AddConstraint(
            model_name='country',
            constraint=models.UniqueConstraint(fields=('country',), name='uniqueCountry'),
        ),
    ]
