# Generated by Django 3.2.3 on 2021-07-16 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characteristics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='active_bool',
            field=models.BooleanField(default=False),
        ),
    ]
