# Generated by Django 3.2.3 on 2021-07-21 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characteristics', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appltype',
            constraint=models.UniqueConstraint(fields=('application_type',), name='applicationTypeUniqueConstraint'),
        ),
    ]
