# Generated by Django 3.2.3 on 2021-08-31 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('characteristics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.ManyToManyField(to='characteristics.Country')),
            ],
        ),
    ]
