# Generated by Django 3.2.9 on 2021-12-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('characteristics', '0002_feecategory'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='languagecountry',
            name='LanguageCountryUniqueDefaultConstraint',
        ),
        migrations.AddConstraint(
            model_name='languagecountry',
            constraint=models.UniqueConstraint(condition=models.Q(('default', True)),
                                               fields=('language', 'country', 'appl_type'),
                                               name='LanguageCountryUniqueDefaultConstraint'),
        ),
    ]
