# Generated by Django 3.2.3 on 2021-09-01 22:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('characteristics', '0002_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='languages',
            name='words_per_page',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
