# Generated by Django 3.2.5 on 2021-10-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('characteristics', '0003_languages_words_per_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='available_appl_types',
            field=models.ManyToManyField(to='characteristics.ApplType'),
        ),
    ]
