# Generated by Django 4.0.1 on 2022-01-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('characteristics', '0003_auto_20211219_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='isa_countries',
            field=models.ManyToManyField(to='characteristics.Country'),
        ),
    ]
