# Generated by Django 3.2.5 on 2021-10-10 22:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('characteristics', '0004_country_available_appl_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='isa_countries',
            field=models.ManyToManyField(related_name='_characteristics_country_isa_countries_+',
                                         to='characteristics.Country'),
        ),
    ]
