# Generated by Django 4.0.2 on 2022-02-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('characteristics', '0004_alter_country_isa_countries'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailedFeeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
