# Generated by Django 4.0.2 on 2022-02-04 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('characteristics', '0005_detailedfeecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailedfeecategory',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='characteristics.country'),
            preserve_default=False,
        ),
    ]
