# Generated by Django 3.2.3 on 2021-10-22 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('characteristics', '0006_auto_20211013_0700'),
    ]

    operations = [
        migrations.CreateModel(
            name='EPValidationTranslationRequired',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('applicable_bool', models.BooleanField(default=False)),
            ],
        ),
        # migrations.AddField(
        #     model_name='country',
        #     name='ep_validation_translation_required',
        #     field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='characteristics.epvalidationtranslationrequired'),
        #     preserve_default=False,
        # ),
    ]
