# Generated by Django 4.0.2 on 2022-02-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('characteristics', '0007_detailedfeecategory_unique_country_and_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='detailedfeecategory',
            name='UniqueNameCountryConstraint',
        ),
        migrations.AddField(
            model_name='detailedfeecategory',
            name='appl_types',
            field=models.ManyToManyField(to='characteristics.ApplType'),
        ),
    ]
