# Generated by Django 3.2.3 on 2021-10-22 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('characteristics', '0007_auto_20211022_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='ep_validation_translation_required',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='characteristics.epvalidationtranslationrequired'),
            preserve_default=False,
        ),
    ]
