# Generated by Django 4.0.2 on 2022-02-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('characteristics', '0008_remove_detailedfeecategory_uniquenamecountryconstraint_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='detailedfeecategory',
            constraint=models.UniqueConstraint(fields=('name', 'country'), name='UniqueNameCountryConstraint'),
        ),
    ]
