# Generated by Django 3.2.3 on 2021-10-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('characteristics', '0008_country_ep_validation_translation_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='entity_size_available',
            field=models.BooleanField(default=False),
        ),
    ]
