# Generated by Django 3.2.3 on 2021-11-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('characteristics', '0009_country_entity_size_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='available_entity_sizes',
            field=models.ManyToManyField(to='characteristics.EntitySize'),
        ),
    ]
