# Generated by Django 4.0.2 on 2022-02-17 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('characteristics', '0009_detailedfeecategory_uniquenamecountryconstraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationRequiredOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        # migrations.AddField(
        #     model_name='country',
        #     name='utility_translation_required',
        #     field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='characteristics.translationrequiredoptions'),
        #     preserve_default=False,
        # ),
    ]
