# Generated by Django 3.2.3 on 2021-11-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('characteristics', '0010_country_available_entity_sizes'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
