# Generated by Django 4.0.2 on 2022-02-17 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('characteristics', '0011_translationrequired_add_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='utility_translation_required',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT,
                                    to='characteristics.translationrequiredoptions'),
            preserve_default=False,
        ),
    ]
