# Generated by Django 3.2.3 on 2021-11-24 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('characteristics', '0011_docformat'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocFormatCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default', models.BooleanField(default=False)),
                ('country',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristics.country')),
                ('doc_format',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristics.docformat')),
            ],
        ),
        migrations.AddConstraint(
            model_name='docformatcountry',
            constraint=models.UniqueConstraint(fields=('doc_format', 'country'),
                                               name='DocFormatCountryUniqueConstraint'),
        ),
        migrations.AddConstraint(
            model_name='docformatcountry',
            constraint=models.UniqueConstraint(condition=models.Q(('default', True)), fields=('country',),
                                               name='DocFormatCountryUniqueDefaultConstraint'),
        ),
    ]
