# Generated by Django 3.2.3 on 2021-11-24 23:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('characteristics', '0012_auto_20211124_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='available_doc_formats',
            field=models.ManyToManyField(related_name='avail_doc_formats', through='characteristics.DocFormatCountry',
                                         to='characteristics.DocFormat'),
        ),
    ]
