# Generated by Django 3.2.3 on 2021-11-26 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('characteristics', '0013_country_available_doc_formats'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='docformatcountry',
            name='DocFormatCountryUniqueConstraint',
        ),
        migrations.RemoveConstraint(
            model_name='docformatcountry',
            name='DocFormatCountryUniqueDefaultConstraint',
        ),
        migrations.AddField(
            model_name='docformatcountry',
            name='appl_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='characteristics.appltype'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='docformatcountry',
            constraint=models.UniqueConstraint(fields=('doc_format', 'country', 'appl_type'),
                                               name='DocFormatCountryUniqueConstraint'),
        ),
        migrations.AddConstraint(
            model_name='docformatcountry',
            constraint=models.UniqueConstraint(condition=models.Q(('default', True)), fields=('country', 'appl_type'),
                                               name='DocFormatCountryUniqueDefaultConstraint'),
        ),
    ]
