# Generated by Django 3.2.3 on 2021-11-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('characteristics', '0014_auto_20211126_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='entity_size_available',
        ),
        migrations.AlterField(
            model_name='country',
            name='available_doc_formats',
            field=models.ManyToManyField(related_name='available_doc_formats',
                                         through='characteristics.DocFormatCountry', to='characteristics.DocFormat'),
        ),
    ]
