# Generated by Django 3.2.3 on 2021-11-29 17:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('characteristics', '0016_auto_20211129_1739'),
        ('estimation', '0035_auto_20211129_1739'),
        ('famform', '0035_alter_customappldetails_language'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Languages',
        ),
    ]
