# Generated by Django 3.2.3 on 2021-11-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('characteristics', '0018_languagecountry'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='available_languages',
            field=models.ManyToManyField(related_name='available_languages', through='characteristics.LanguageCountry',
                                         to='characteristics.Language'),
        ),
        migrations.AddConstraint(
            model_name='languagecountry',
            constraint=models.UniqueConstraint(fields=('language', 'country', 'appl_type'),
                                               name='LanguageCountryUniqueConstraint'),
        ),
        migrations.AddConstraint(
            model_name='languagecountry',
            constraint=models.UniqueConstraint(condition=models.Q(('default', True)), fields=('language', 'appl_type'),
                                               name='LanguageCountryUniqueDefaultConstraint'),
        ),
    ]
