# Generated by Django 3.2.3 on 2021-12-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('characteristics', '0019_auto_20211129_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='ep_official_language_bool',
            field=models.BooleanField(default=False),
        ),
    ]
