# Generated by Django 3.2.3 on 2021-12-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('characteristics', '0020_language_ep_official_language_bool'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationImplementedPseudoEnum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
