# Generated by Django 3.2.3 on 2021-12-03 00:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('characteristics', '0021_translationimplementedpseudoenum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epvalidationtranslationrequired',
            name='applicable_bool',
        ),
    ]
