# Generated by Django 3.2.9 on 2021-12-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('characteristics', '0022_remove_epvalidationtranslationrequired_applicable_bool'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitysize',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
