# Generated by Django 3.2.9 on 2021-12-03 21:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('characteristics', '0023_entitysize_default'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entitysize',
            old_name='default',
            new_name='default_bool',
        ),
    ]
