# Generated by Django 3.2.9 on 2021-12-04 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('characteristics', '0024_rename_default_entitysize_default_bool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='available_entity_sizes',
        ),
        migrations.AddField(
            model_name='entitysize',
            name='country',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE,
                                    to='characteristics.country'),
            preserve_default=False,
        ),
    ]
