# Generated by Django 3.2.9 on 2021-12-04 04:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('characteristics', '0025_auto_20211204_0310'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='entitysize',
            name='entitySizeUniqueConstraint',
        ),
        migrations.AddConstraint(
            model_name='entitysize',
            constraint=models.UniqueConstraint(fields=('entity_size', 'country'),
                                               name='entitySizeCountryUniqueConstraint'),
        ),
        migrations.AddConstraint(
            model_name='entitysize',
            constraint=models.UniqueConstraint(condition=models.Q(('default_bool', True)), fields=('country',),
                                               name='DefaultEntitySizeCountryUniqueConstraint'),
        ),
    ]
