# Generated by Django 4.0.2 on 2022-03-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('lawfirm', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawfirm',
            name='long_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
