# Generated by Django 4.0.2 on 2022-03-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('lawfirm', '0003_lawfirm_long_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultlawfirm',
            name='hourly',
        ),
        migrations.RemoveField(
            model_name='defaultlawfirm',
            name='hourly_currency',
        ),
        migrations.RemoveField(
            model_name='lawfirm',
            name='hourly',
        ),
        migrations.RemoveField(
            model_name='lawfirm',
            name='hourly_currency',
        ),
        migrations.AddField(
            model_name='defaultlawfirm',
            name='long_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
