# Generated by Django 4.0.2 on 2022-03-16 10:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('lawfirm', '0004_remove_defaultlawfirm_hourly_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawfirm',
            name='user',
        ),
    ]
