# Generated by Django 4.0.2 on 2022-03-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('lawfirm', '0005_remove_lawfirm_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawfirm',
            name='email',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lawfirm',
            name='phone',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lawfirm',
            name='website',
            field=models.CharField(default=11, max_length=255),
            preserve_default=False,
        ),
    ]
