# Generated by Django 4.0.2 on 2022-03-16 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('lawfirm', '0006_lawfirm_email_lawfirm_phone_lawfirm_website'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='lawfirm',
            constraint=models.UniqueConstraint(fields=('name',), name='LawFirmNameUniqueConstraint'),
        ),
    ]
