# Generated by Django 4.0.2 on 2022-03-18 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('lawfirm', '0010_lawfirmimages_remove_lawfirm_image_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawfirm',
            name='image_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lawfirm.lawfirmimages'),
            preserve_default=False,
        ),
    ]
