# Generated by Django 4.0.2 on 2022-03-18 08:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('lawfirm', '0011_lawfirm_image_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawfirm',
            name='image_location',
        ),
        migrations.DeleteModel(
            name='LawFirmImages',
        ),
    ]
