# Generated by Django 4.0.2 on 2022-03-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('lawfirm', '0012_remove_lawfirm_image_location_delete_lawfirmimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawfirm',
            name='image_location',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
