# Generated by Django 4.0.2 on 2022-03-28 01:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('lawfirm', '0013_lawfirm_image_location'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='lawfirm',
            constraint=models.UniqueConstraint(fields=('slug',), name='LawFirmSlugUniqueConstraint'),
        ),
    ]
