# Generated by Django 4.0.2 on 2022-03-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('lawfirm', '0014_lawfirm_lawfirmsluguniqueconstraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawfirm',
            name='image_location',
            field=models.CharField(default='default', max_length=255),
        ),
    ]
