# Generated by Django 4.0.2 on 2022-04-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('lawfirm', '0015_alter_lawfirm_image_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawfirm',
            name='image_location',
            field=models.ImageField(upload_to='lawfirm'),
        ),
    ]
