# Generated by Django 3.2.9 on 2021-12-15 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.TextField()),
                ('family_no', models.CharField(default='', max_length=20)),
                ('unique_display_no', models.IntegerField()),
            ],
        ),
    ]
