# Generated by Django 3.2.5 on 2021-10-07 04:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('family', '0002_family_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='unique_display_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
