# Generated by Django 3.2.3 on 2021-07-03 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_initial'),
        ('estimation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filingestimate',
            name='application',
        ),
        migrations.AddField(
            model_name='baseest',
            name='application',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.baseapplication'),
            preserve_default=False,
        ),
    ]
