# Generated by Django 3.2.9 on 2021-12-16 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('characteristics', '0002_feecategory'),
        ('estimation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowanceesttemplate',
            name='fee_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristics.feecategory'),
        ),
        migrations.AlterField(
            model_name='filingestimatetemplate',
            name='fee_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristics.feecategory'),
        ),
        migrations.AlterField(
            model_name='issueesttemplate',
            name='fee_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristics.feecategory'),
        ),
        migrations.AlterField(
            model_name='oaestimatetemplate',
            name='fee_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristics.feecategory'),
        ),
        migrations.AlterField(
            model_name='publicationesttemplate',
            name='fee_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristics.feecategory'),
        ),
        migrations.AlterField(
            model_name='requestexamesttemplate',
            name='fee_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristics.feecategory'),
        ),
        migrations.DeleteModel(
            name='FeeCategory',
        ),
    ]
