# Generated by Django 3.2.3 on 2021-07-14 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characteristics', '0001_initial'),
        ('estimation', '0002_auto_20210703_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowanceesttemplate',
            name='appl_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='characteristics.appltype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filingestimatetemplate',
            name='appl_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='characteristics.appltype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issueesttemplate',
            name='appl_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='characteristics.appltype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oaestimatetemplate',
            name='appl_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='characteristics.appltype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicationesttemplate',
            name='appl_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='characteristics.appltype'),
            preserve_default=False,
        ),
    ]
