# Generated by Django 3.2.10 on 2021-12-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('estimation', '0002_auto_20211216_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allowanceesttemplate',
            name='isa_country_fee_only',
        ),
        migrations.RemoveField(
            model_name='filingestimatetemplate',
            name='isa_country_fee_only',
        ),
        migrations.RemoveField(
            model_name='issueesttemplate',
            name='isa_country_fee_only',
        ),
        migrations.RemoveField(
            model_name='oaestimatetemplate',
            name='isa_country_fee_only',
        ),
        migrations.RemoveField(
            model_name='publicationesttemplate',
            name='isa_country_fee_only',
        ),
        migrations.RemoveField(
            model_name='requestexamesttemplate',
            name='isa_country_fee_only',
        ),
        migrations.AddField(
            model_name='lineestimationtemplateconditions',
            name='isa_country_fee_only',
            field=models.BooleanField(default=False),
        ),
    ]
