# Generated by Django 4.0.2 on 2022-02-03 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('characteristics', '0005_detailedfeecategory'),
        ('estimation', '0003_auto_20211230_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowanceesttemplate',
            name='detailed_fee_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='characteristics.detailedfeecategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filingestimatetemplate',
            name='detailed_fee_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='characteristics.detailedfeecategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issueesttemplate',
            name='detailed_fee_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='characteristics.detailedfeecategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oaestimatetemplate',
            name='detailed_fee_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='characteristics.detailedfeecategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicationesttemplate',
            name='detailed_fee_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='characteristics.detailedfeecategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestexamesttemplate',
            name='detailed_fee_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='characteristics.detailedfeecategory'),
            preserve_default=False,
        ),
    ]
