# Generated by Django 3.2.3 on 2021-07-15 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0003_auto_20210714_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowanceesttemplate',
            name='conditions',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estimation.lineestimationtemplateconditions'),
        ),
        migrations.AlterField(
            model_name='filingestimatetemplate',
            name='conditions',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estimation.lineestimationtemplateconditions'),
        ),
        migrations.AlterField(
            model_name='issueesttemplate',
            name='conditions',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estimation.lineestimationtemplateconditions'),
        ),
        migrations.AlterField(
            model_name='oaestimatetemplate',
            name='conditions',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estimation.lineestimationtemplateconditions'),
        ),
        migrations.AlterField(
            model_name='publicationesttemplate',
            name='conditions',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estimation.lineestimationtemplateconditions'),
        ),
    ]
