# Generated by Django 3.2.3 on 2021-08-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('estimation', '0003_auto_20210820_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineestimationtemplateconditions',
            name='condition_indep_claims_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lineestimationtemplateconditions',
            name='condition_indep_claims_min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
