# Generated by Django 4.0.2 on 2022-02-04 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('characteristics', '0006_detailedfeecategory_country'),
        ('estimation', '0004_allowanceesttemplate_detailed_fee_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowanceesttemplate',
            name='appl_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='characteristics.appltype'),
        ),
        migrations.AlterField(
            model_name='allowanceesttemplate',
            name='conditions',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT,
                                       to='estimation.lineestimationtemplateconditions'),
        ),
        migrations.AlterField(
            model_name='allowanceesttemplate',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='characteristics.country'),
        ),
        migrations.AlterField(
            model_name='allowanceesttemplate',
            name='detailed_fee_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    to='characteristics.detailedfeecategory'),
        ),
        migrations.AlterField(
            model_name='allowanceesttemplate',
            name='fee_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='characteristics.feecategory'),
        ),
        migrations.AlterField(
            model_name='allowanceesttemplate',
            name='law_firm_template',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='estimation.lawfirmesttemplate'),
        ),
        migrations.AlterField(
            model_name='filingestimatetemplate',
            name='appl_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='characteristics.appltype'),
        ),
        migrations.AlterField(
            model_name='filingestimatetemplate',
            name='conditions',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT,
                                       to='estimation.lineestimationtemplateconditions'),
        ),
        migrations.AlterField(
            model_name='filingestimatetemplate',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='characteristics.country'),
        ),
        migrations.AlterField(
            model_name='filingestimatetemplate',
            name='detailed_fee_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    to='characteristics.detailedfeecategory'),
        ),
        migrations.AlterField(
            model_name='filingestimatetemplate',
            name='fee_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='characteristics.feecategory'),
        ),
        migrations.AlterField(
            model_name='filingestimatetemplate',
            name='law_firm_template',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='estimation.lawfirmesttemplate'),
        ),
        migrations.AlterField(
            model_name='issueesttemplate',
            name='appl_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='characteristics.appltype'),
        ),
        migrations.AlterField(
            model_name='issueesttemplate',
            name='conditions',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT,
                                       to='estimation.lineestimationtemplateconditions'),
        ),
        migrations.AlterField(
            model_name='issueesttemplate',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='characteristics.country'),
        ),
        migrations.AlterField(
            model_name='issueesttemplate',
            name='detailed_fee_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    to='characteristics.detailedfeecategory'),
        ),
        migrations.AlterField(
            model_name='issueesttemplate',
            name='fee_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='characteristics.feecategory'),
        ),
        migrations.AlterField(
            model_name='issueesttemplate',
            name='law_firm_template',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='estimation.lawfirmesttemplate'),
        ),
        migrations.AlterField(
            model_name='oaestimatetemplate',
            name='appl_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='characteristics.appltype'),
        ),
        migrations.AlterField(
            model_name='oaestimatetemplate',
            name='conditions',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT,
                                       to='estimation.lineestimationtemplateconditions'),
        ),
        migrations.AlterField(
            model_name='oaestimatetemplate',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='characteristics.country'),
        ),
        migrations.AlterField(
            model_name='oaestimatetemplate',
            name='detailed_fee_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    to='characteristics.detailedfeecategory'),
        ),
        migrations.AlterField(
            model_name='oaestimatetemplate',
            name='fee_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='characteristics.feecategory'),
        ),
        migrations.AlterField(
            model_name='oaestimatetemplate',
            name='law_firm_template',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='estimation.lawfirmesttemplate'),
        ),
        migrations.AlterField(
            model_name='publicationesttemplate',
            name='appl_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='characteristics.appltype'),
        ),
        migrations.AlterField(
            model_name='publicationesttemplate',
            name='conditions',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT,
                                       to='estimation.lineestimationtemplateconditions'),
        ),
        migrations.AlterField(
            model_name='publicationesttemplate',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='characteristics.country'),
        ),
        migrations.AlterField(
            model_name='publicationesttemplate',
            name='detailed_fee_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    to='characteristics.detailedfeecategory'),
        ),
        migrations.AlterField(
            model_name='publicationesttemplate',
            name='fee_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='characteristics.feecategory'),
        ),
        migrations.AlterField(
            model_name='publicationesttemplate',
            name='law_firm_template',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='estimation.lawfirmesttemplate'),
        ),
        migrations.AlterField(
            model_name='requestexamesttemplate',
            name='appl_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='characteristics.appltype'),
        ),
        migrations.AlterField(
            model_name='requestexamesttemplate',
            name='conditions',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT,
                                       to='estimation.lineestimationtemplateconditions'),
        ),
        migrations.AlterField(
            model_name='requestexamesttemplate',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='characteristics.country'),
        ),
        migrations.AlterField(
            model_name='requestexamesttemplate',
            name='detailed_fee_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    to='characteristics.detailedfeecategory'),
        ),
        migrations.AlterField(
            model_name='requestexamesttemplate',
            name='fee_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='characteristics.feecategory'),
        ),
        migrations.AlterField(
            model_name='requestexamesttemplate',
            name='law_firm_template',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='estimation.lawfirmesttemplate'),
        ),
    ]
