# Generated by Django 3.2.3 on 2021-08-24 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('estimation', '0004_auto_20210820_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usoaestimatetemplate',
            name='oa_type',
        ),
        migrations.AddField(
            model_name='usoaestimatetemplate',
            name='oa_final_bool',
            field=models.BooleanField(default=False),
        ),
    ]
