# Generated by Django 3.2.3 on 2021-07-15 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characteristics', '0001_initial'),
        ('estimation', '0004_auto_20210715_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineestimationtemplateconditions',
            name='condition_entity_size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='characteristics.entitysize'),
        ),
    ]
