# Generated by Django 3.2.3 on 2021-08-24 23:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('estimation', '0005_auto_20210824_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='usoaestimatetemplate',
            name='oa_first_final_bool',
            field=models.BooleanField(default=False),
        ),
    ]
