# Generated by Django 3.2.3 on 2021-07-15 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0005_alter_lineestimationtemplateconditions_condition_entity_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowanceesttemplate',
            name='law_firm_template',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='estimation.lawfirmesttemplate'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filingestimatetemplate',
            name='law_firm_template',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='estimation.lawfirmesttemplate'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issueesttemplate',
            name='law_firm_template',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='estimation.lawfirmesttemplate'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='oaestimatetemplate',
            name='law_firm_template',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='estimation.lawfirmesttemplate'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publicationesttemplate',
            name='law_firm_template',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='estimation.lawfirmesttemplate'),
            preserve_default=False,
        ),
    ]
