# Generated by Django 3.2.3 on 2021-08-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('estimation', '0006_usoaestimatetemplate_oa_first_final_bool'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowanceesttemplate',
            name='prior_pct_same_country',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='filingestimatetemplate',
            name='prior_pct_same_country',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='issueesttemplate',
            name='prior_pct_same_country',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='oaestimatetemplate',
            name='prior_pct_same_country',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publicationesttemplate',
            name='prior_pct_same_country',
            field=models.BooleanField(default=False),
        ),
    ]
