# Generated by Django 3.2.3 on 2021-08-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('estimation', '0007_auto_20210826_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineestimationtemplateconditions',
            name='condition_annual_prosecution_fee',
            field=models.BooleanField(default=False),
        ),
    ]
