# Generated by Django 4.0.2 on 2022-04-28 20:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('estimation', '0007_lineestimationtemplateconditions_condition_renewal_fee_from_filing_after_grant'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowanceesttemplate',
            name='date_disabled',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='allowanceesttemplate',
            name='date_enabled',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='filingestimatetemplate',
            name='date_disabled',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='filingestimatetemplate',
            name='date_enabled',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='issueesttemplate',
            name='date_disabled',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='issueesttemplate',
            name='date_enabled',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='oaestimatetemplate',
            name='date_disabled',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='oaestimatetemplate',
            name='date_enabled',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='publicationesttemplate',
            name='date_disabled',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='publicationesttemplate',
            name='date_enabled',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='requestexamesttemplate',
            name='date_disabled',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='requestexamesttemplate',
            name='date_enabled',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
