# Generated by Django 3.2.3 on 2021-09-02 18:16

from django.db import migrations
import relativedeltafield.fields


class Migration(migrations.Migration):
    dependencies = [
        ('estimation', '0011_auto_20210902_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaulttranslationesttemplate',
            name='date_diff',
            field=relativedeltafield.fields.RelativeDeltaField(default='P0D'),
            preserve_default=False,
        ),
    ]
