# Generated by Django 3.2.3 on 2021-09-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('estimation', '0012_defaulttranslationesttemplate_date_diff'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowanceesttemplate',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allowanceesttemplate',
            name='fee_code',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filingestimatetemplate',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filingestimatetemplate',
            name='fee_code',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issueesttemplate',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issueesttemplate',
            name='fee_code',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oaestimatetemplate',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oaestimatetemplate',
            name='fee_code',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicationesttemplate',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicationesttemplate',
            name='fee_code',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
