# Generated by Django 3.2.3 on 2021-09-08 22:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('estimation', '0013_auto_20210907_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowanceesttemplate',
            name='prior_pct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='filingestimatetemplate',
            name='prior_pct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='issueesttemplate',
            name='prior_pct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='oaestimatetemplate',
            name='prior_pct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publicationesttemplate',
            name='prior_pct',
            field=models.BooleanField(default=False),
        ),
    ]
