# Generated by Django 3.2.3 on 2021-09-08 23:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('estimation', '0014_auto_20210908_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowanceesttemplate',
            name='prior_pct',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='allowanceesttemplate',
            name='prior_pct_same_country',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='filingestimatetemplate',
            name='prior_pct',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='filingestimatetemplate',
            name='prior_pct_same_country',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='issueesttemplate',
            name='prior_pct',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='issueesttemplate',
            name='prior_pct_same_country',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='oaestimatetemplate',
            name='prior_pct',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='oaestimatetemplate',
            name='prior_pct_same_country',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='publicationesttemplate',
            name='prior_pct',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='publicationesttemplate',
            name='prior_pct_same_country',
            field=models.BooleanField(null=True),
        ),
    ]
