# Generated by Django 3.2.3 on 2021-09-09 05:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('estimation', '0015_auto_20210908_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allowanceesttemplate',
            name='prior_pct',
        ),
        migrations.RemoveField(
            model_name='allowanceesttemplate',
            name='prior_pct_same_country',
        ),
        migrations.RemoveField(
            model_name='filingestimatetemplate',
            name='prior_pct',
        ),
        migrations.RemoveField(
            model_name='filingestimatetemplate',
            name='prior_pct_same_country',
        ),
        migrations.RemoveField(
            model_name='issueesttemplate',
            name='prior_pct',
        ),
        migrations.RemoveField(
            model_name='issueesttemplate',
            name='prior_pct_same_country',
        ),
        migrations.RemoveField(
            model_name='oaestimatetemplate',
            name='prior_pct',
        ),
        migrations.RemoveField(
            model_name='oaestimatetemplate',
            name='prior_pct_same_country',
        ),
        migrations.RemoveField(
            model_name='publicationesttemplate',
            name='prior_pct',
        ),
        migrations.RemoveField(
            model_name='publicationesttemplate',
            name='prior_pct_same_country',
        ),
        migrations.AddField(
            model_name='lineestimationtemplateconditions',
            name='prior_pct',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='lineestimationtemplateconditions',
            name='prior_pct_same_country',
            field=models.BooleanField(null=True),
        ),
    ]
