# Generated by Django 3.2.3 on 2021-09-11 05:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('estimation', '0016_auto_20210909_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineestimationtemplateconditions',
            name='prev_appl_date_excl_intermediary_time',
            field=models.BooleanField(default=False),
        ),
    ]
