# Generated by Django 3.2.3 on 2021-09-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('estimation', '0017_lineestimationtemplateconditions_prev_appl_date_excl_intermediary_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineestimationtemplateconditions',
            name='condition_pages_desc_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lineestimationtemplateconditions',
            name='condition_pages_desc_min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
