# Generated by Django 3.2.3 on 2021-10-03 21:21

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ('estimation', '0019_auto_20210915_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaulttranslationesttemplate',
            name='cost_per_word',
            field=djmoney.models.fields.MoneyField(decimal_places=4, default=Decimal('0'), default_currency='USD',
                                                   max_digits=19),
        ),
        migrations.AlterField(
            model_name='translationesttemplate',
            name='cost_per_word',
            field=djmoney.models.fields.MoneyField(decimal_places=4, default=Decimal('0'), default_currency='USD',
                                                   max_digits=19),
        ),
    ]
