# Generated by Django 3.2.3 on 2021-11-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('estimation', '0023_lineestimationtemplateconditions_condition_annual_prosecution_fee_until_grant'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineestimationtemplateconditions',
            name='condition_renewal_fee_from_filing_after_grant',
            field=models.BooleanField(default=False),
        ),
    ]
