# Generated by Django 3.2.3 on 2021-11-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('estimation', '0024_lineestimationtemplateconditions_condition_renewal_fee_from_filing_after_grant'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowanceesttemplate',
            name='isa_country_fee_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='filingestimatetemplate',
            name='isa_country_fee_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='issueesttemplate',
            name='isa_country_fee_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='oaestimatetemplate',
            name='isa_country_fee_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publicationesttemplate',
            name='isa_country_fee_only',
            field=models.BooleanField(default=False),
        ),
    ]
