# Generated by Django 3.2.3 on 2021-11-19 14:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('estimation', '0025_auto_20211113_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineestimationtemplateconditions',
            old_name='condition_pages_max',
            new_name='condition_pages_total_max',
        ),
        migrations.RenameField(
            model_name='lineestimationtemplateconditions',
            old_name='condition_pages_min',
            new_name='condition_pages_total_min',
        ),
    ]
