# Generated by Django 3.2.3 on 2021-11-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('estimation', '0026_auto_20211119_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineestimationtemplateconditions',
            name='condition_pages_claims_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lineestimationtemplateconditions',
            name='condition_pages_claims_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lineestimationtemplateconditions',
            name='condition_pages_drawings_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lineestimationtemplateconditions',
            name='condition_pages_drawings_min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
