# Generated by Django 3.2.3 on 2021-11-22 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('application', '0014_requestexamination'),
        ('estimation', '0029_requestexamesttemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestExamEst',
            fields=[
                ('baseest_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='estimation.baseest')),
                ('exam_request',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.requestexamination')),
            ],
            options={
                'abstract': False,
            },
            bases=('estimation.baseest',),
        ),
    ]
