# Generated by Django 3.2.3 on 2021-11-28 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('estimation', '0032_feecategory_run_python'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowanceesttemplate',
            name='fee_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='estimation.feecategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filingestimatetemplate',
            name='fee_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='estimation.feecategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issueesttemplate',
            name='fee_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='estimation.feecategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oaestimatetemplate',
            name='fee_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='estimation.feecategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicationesttemplate',
            name='fee_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='estimation.feecategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestexamesttemplate',
            name='fee_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='estimation.feecategory'),
            preserve_default=False,
        ),
    ]
