# Generated by Django 3.2.3 on 2021-11-29 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('characteristics', '0015_auto_20211128_1842'),
        ('estimation', '0033_auto_20211128_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineestimationtemplateconditions',
            name='language',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='characteristics.Languages'),
        ),
    ]
