# Generated by Django 3.2.3 on 2021-11-29 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('characteristics', '0016_auto_20211129_1739'),
        ('estimation', '0034_lineestimationtemplateconditions_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineestimationtemplateconditions',
            name='language',
        ),
        migrations.AlterField(
            model_name='translationesttemplate',
            name='end_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_language_est_temp',
                                    to='characteristics.language'),
        ),
        migrations.AlterField(
            model_name='translationesttemplate',
            name='start_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_language_est_temp',
                                    to='characteristics.language'),
        ),
    ]
