# Generated by Django 3.2.5 on 2021-08-04 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characteristics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_allowance', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApplDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_indep_claims', models.IntegerField()),
                ('num_pages', models.IntegerField()),
                ('num_claims', models.IntegerField()),
                # ('num_pages_drawings', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BaseApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('date_filing', models.DateField()),
                ('country',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristics.country')),
                ('details',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='application.appldetails')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EPValidationIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_issuance', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_issuance', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BaseUtilityApplication',
            fields=[
                ('baseapplication_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='application.baseapplication')),
            ],
            options={
                'abstract': False,
            },
            bases=('application.baseapplication',),
        ),
        migrations.CreateModel(
            name='EPValidationApplication',
            fields=[
                ('baseapplication_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='application.baseapplication')),
            ],
            options={
                'abstract': False,
            },
            bases=('application.baseapplication',),
        ),
        migrations.CreateModel(
            name='PCTApplication',
            fields=[
                ('baseapplication_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='application.baseapplication')),
            ],
            options={
                'abstract': False,
            },
            bases=('application.baseapplication',),
        ),
        migrations.CreateModel(
            name='ProvApplication',
            fields=[
                ('baseapplication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='application.baseapplication')),
            ],
            options={
                'abstract': False,
            },
            bases=('application.baseapplication',),
        ),
        migrations.CreateModel(
            name='USOfficeAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_office_action', models.DateField()),
                ('oa_final_bool', models.BooleanField(default=False)),
                ('oa_prev', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.usofficeaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_publication', models.DateField()),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='application.baseapplication')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfficeAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_office_action', models.DateField()),
                ('oa_prev', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.officeaction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
