# Generated by Django 3.2.5 on 2021-07-25 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0001_initial'),
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseapplication',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family.family'),
        ),
        migrations.AddField(
            model_name='baseapplication',
            name='prior_appl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.baseapplication'),
        ),
    ]
