# Generated by Django 3.2.9 on 2021-12-15 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0001_initial'),
        ('characteristics', '0001_initial'),
        ('famform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseapplication',
            name='appl_option',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='famform.apploptions'),
        ),
        migrations.AddField(
            model_name='baseapplication',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristics.country'),
        ),
        migrations.AddField(
            model_name='baseapplication',
            name='details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='application.appldetails'),
        ),
    ]
