# Generated by Django 3.2.9 on 2021-12-15 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0002_initial'),
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseapplication',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family.family'),
        ),
        migrations.AddField(
            model_name='baseapplication',
            name='prior_appl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='application.baseapplication'),
        ),
    ]
