# Generated by Django 3.2.3 on 2021-07-21 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('characteristics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appldetails',
            name='entity_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristics.entitysize'),
        ),
        migrations.CreateModel(
            name='USUtilityApplication',
            fields=[
                ('baseutilityapplication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='application.baseutilityapplication')),
            ],
            options={
                'abstract': False,
            },
            bases=('application.baseutilityapplication',),
        ),
        migrations.CreateModel(
            name='UtilityApplication',
            fields=[
                ('baseutilityapplication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='application.baseutilityapplication')),
            ],
            options={
                'abstract': False,
            },
            bases=('application.baseutilityapplication',),
        ),
        migrations.AddField(
            model_name='officeaction',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.baseutilityapplication'),
        ),
        migrations.AddField(
            model_name='issue',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='application.baseutilityapplication'),
        ),
        migrations.AddField(
            model_name='allowance',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='application.baseutilityapplication'),
        ),
        migrations.AddField(
            model_name='usofficeaction',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.usutilityapplication'),
        ),
    ]
