# Generated by Django 3.2.3 on 2021-08-04 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('famform', '0003_initial'),
        ('application', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseapplication',
            name='appl_option',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE,
                                       to='famform.apploptions'),
            preserve_default=False,
        ),
    ]
