# Generated by Django 3.2.9 on 2021-12-15 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0003_initial'),
        ('characteristics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appldetails',
            name='entity_size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='characteristics.entitysize'),
        ),
        migrations.AddField(
            model_name='appldetails',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristics.language'),
        ),
        migrations.CreateModel(
            name='EPApplication',
            fields=[
                ('baseutilityapplication_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='application.baseutilityapplication')),
            ],
            options={
                'abstract': False,
            },
            bases=('application.baseutilityapplication',),
        ),
        migrations.CreateModel(
            name='USUtilityApplication',
            fields=[
                ('baseutilityapplication_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='application.baseutilityapplication')),
            ],
            options={
                'abstract': False,
            },
            bases=('application.baseutilityapplication',),
        ),
        migrations.CreateModel(
            name='UtilityApplication',
            fields=[
                ('baseutilityapplication_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='application.baseutilityapplication')),
            ],
            options={
                'abstract': False,
            },
            bases=('application.baseutilityapplication',),
        ),
        migrations.AddField(
            model_name='pctapplication',
            name='isa_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristics.country'),
        ),
        migrations.AddField(
            model_name='officeaction',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='application.baseutilityapplication'),
        ),
        migrations.AddField(
            model_name='issue',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                       to='application.baseutilityapplication'),
        ),
        migrations.AddField(
            model_name='epvalidationissue',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                       to='application.epvalidationapplication'),
        ),
        migrations.AddField(
            model_name='allowance',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                       to='application.baseutilityapplication'),
        ),
        migrations.AddField(
            model_name='usofficeaction',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.usutilityapplication'),
        ),
    ]
