# Generated by Django 3.2.3 on 2021-07-05 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characteristics', '0001_initial'),
        ('application', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseapplication',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='characteristics.country'),
            preserve_default=False,
        ),
    ]
