# Generated by Django 3.2.5 on 2021-07-27 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('application', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseapplication',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='polymorphic_application.baseapplication_set+',
                                    to='contenttypes.contenttype'),
        ),
    ]
