# Generated by Django 3.2.5 on 2021-07-27 04:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('application', '0004_baseapplication_polymorphic_ctype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseapplication',
            name='polymorphic_ctype',
        ),
    ]
