# Generated by Django 3.2.3 on 2021-07-18 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_baseapplication_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officeaction',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.baseutilityapplication'),
        ),
    ]
