# Generated by Django 3.2.9 on 2021-12-20 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('application', '0005_remove_allowance_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowance',
            name='application',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE,
                                       to='application.baseutilityapplication'),
        ),
    ]
