# Generated by Django 3.2.10 on 2021-12-29 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('estimation', '0002_auto_20211216_0838'),
        ('application', '0007_re_add_data_for_allowance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowance',
            name='application',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allowance',
                                       to='application.baseutilityapplication'),
        ),
        migrations.AlterField(
            model_name='officeaction',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officeaction_set',
                                    to='application.baseutilityapplication'),
        ),
        migrations.DeleteModel(
            name='UtilityApplication',
        ),
    ]
