# Generated by Django 3.2.3 on 2021-09-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('application', '0007_appldetails_num_pages_drawings'),
    ]

    operations = [
        migrations.AddField(
            model_name='appldetails',
            name='num_pages_description',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
