# Generated by Django 4.0.1 on 2022-01-19 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('characteristics', '0004_alter_country_isa_countries'),
        ('application', '0008_auto_20211229_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='pctapplication',
            name='isa_entity_size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='characteristics.entitysize'),
            preserve_default=False,
        ),
    ]
