# Generated by Django 3.2.3 on 2021-09-15 03:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('application', '0009_rename_num_pages_appldetails_num_pages_claims'),
    ]

    operations = [
        migrations.AddField(
            model_name='appldetails',
            name='num_drawings',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
