# Generated by Django 3.2.5 on 2021-10-10 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('characteristics', '0004_country_available_appl_types'),
        ('application', '0010_appldetails_num_drawings'),
    ]

    operations = [
        migrations.AddField(
            model_name='pctapplication',
            name='isa_country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='characteristics.country'),
            preserve_default=False,
        ),
    ]
