# Generated by Django 3.2.3 on 2021-11-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('application', '0012_alter_appldetails_entity_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='appldetails',
            name='num_claims_multiple_dependent',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
