# Generated by Django 3.2.3 on 2021-11-22 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('application', '0013_appldetails_num_claims_multiple_dependent'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestExamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_request_examination', models.DateField()),
                ('application',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='application.baseapplication')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
