# Generated by Django 3.2.3 on 2021-11-29 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('characteristics', '0017_delete_languages'),
        ('application', '0015_alter_appldetails_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appldetails',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='characteristics.language'),
            preserve_default=False,
        ),
    ]
