# Generated by Django 3.2.3 on 2021-07-21 05:33

from django.db import migrations, models
import django.db.models.deletion
import relativedeltafield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characteristics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultCountryOANum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oa_total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OATransform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_diff', relativedeltafield.fields.RelativeDeltaField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristics.country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='USOATransform',
            fields=[
                ('oatransform_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transform.oatransform')),
                ('final_oa_bool', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('transform.oatransform',),
        ),
        migrations.CreateModel(
            name='PublicationTransform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_diff', relativedeltafield.fields.RelativeDeltaField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristics.country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IssueTransform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_diff', relativedeltafield.fields.RelativeDeltaField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristics.country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DefaultPublTransform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_diff', relativedeltafield.fields.RelativeDeltaField()),
                ('appl_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristics.appltype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DefaultOATransform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_diff', relativedeltafield.fields.RelativeDeltaField()),
                ('appl_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristics.appltype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DefaultIssueTransform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_diff', relativedeltafield.fields.RelativeDeltaField()),
                ('appl_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristics.appltype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DefaultFilingTransform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_diff', relativedeltafield.fields.RelativeDeltaField()),
                ('appl_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristics.appltype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DefaultAllowanceTransform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_diff', relativedeltafield.fields.RelativeDeltaField()),
                ('appl_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristics.appltype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomFilingTransform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_diff', relativedeltafield.fields.RelativeDeltaField()),
                ('appl_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristics.appltype')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristics.country')),
                ('prev_appl_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prev_appl_type', to='characteristics.appltype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CountryOANum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oa_total', models.IntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristics.country')),
            ],
        ),
        migrations.CreateModel(
            name='AllowanceTransform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_diff', relativedeltafield.fields.RelativeDeltaField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristics.country')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
