# Generated by Django 3.2.3 on 2021-08-31 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('characteristics', '0002_languages'),
        ('transform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio_pages_to_en_pages', models.DecimalField(decimal_places=2, max_digits=5)),
                ('language',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='characteristics.languages')),
            ],
        ),
    ]
