# Generated by Django 3.2.9 on 2021-12-16 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('characteristics', '0002_feecategory'),
        ('transform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowancetransform',
            name='appl_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='characteristics.appltype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issuetransform',
            name='appl_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='characteristics.appltype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oatransform',
            name='appl_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='characteristics.appltype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicationtransform',
            name='appl_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='characteristics.appltype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestexaminationtransform',
            name='appl_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='characteristics.appltype'),
            preserve_default=False,
        ),
    ]
