# Generated by Django 3.2.5 on 2021-10-17 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('transform', '0003_delete_languagetranslation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransComplexTimeOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='allowancetransform',
            name='complex_time_conditions',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='transform.transcomplextimeoptions'),
        ),
        migrations.AddField(
            model_name='customfilingtransform',
            name='complex_time_conditions',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='transform.transcomplextimeoptions'),
        ),
        migrations.AddField(
            model_name='issuetransform',
            name='complex_time_conditions',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='transform.transcomplextimeoptions'),
        ),
        migrations.AddField(
            model_name='oatransform',
            name='complex_time_conditions',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='transform.transcomplextimeoptions'),
        ),
        migrations.AddField(
            model_name='publicationtransform',
            name='complex_time_conditions',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='transform.transcomplextimeoptions'),
        ),
    ]
