# Generated by Django 3.2.9 on 2021-12-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('transform', '0004_auto_20211218_0238'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='defaultallowancetransform',
            constraint=models.UniqueConstraint(fields=('appl_type',), name='Appdefaultallowancetransform'),
        ),
        migrations.AddConstraint(
            model_name='defaultfilingtransform',
            constraint=models.UniqueConstraint(fields=('appl_type',), name='Appdefaultfilingtransform'),
        ),
        migrations.AddConstraint(
            model_name='defaultissuetransform',
            constraint=models.UniqueConstraint(fields=('appl_type',), name='Appdefaultissuetransform'),
        ),
        migrations.AddConstraint(
            model_name='defaultoatransform',
            constraint=models.UniqueConstraint(fields=('appl_type',), name='Appdefaultoatransform'),
        ),
        migrations.AddConstraint(
            model_name='defaultpubltransform',
            constraint=models.UniqueConstraint(fields=('appl_type',), name='Appdefaultpubltransform'),
        ),
        migrations.AddConstraint(
            model_name='defaultrequestexaminationtransform',
            constraint=models.UniqueConstraint(fields=('appl_type',), name='Appdefaultrequestexaminationtransform'),
        ),
    ]
