# Generated by Django 3.2.5 on 2021-10-17 06:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('transform', '0004_auto_20211017_0300'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransComplexTimeOptions',
            new_name='TransComplexTime',
        ),
    ]
