# Generated by Django 3.2.3 on 2021-11-22 06:52

from django.db import migrations, models
import django.db.models.deletion
import relativedeltafield.fields


class Migration(migrations.Migration):
    dependencies = [
        ('characteristics', '0010_country_available_entity_sizes'),
        ('transform', '0005_rename_transcomplextimeoptions_transcomplextime'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestExaminationTransform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_diff', relativedeltafield.fields.RelativeDeltaField()),
                ('complex_time_conditions',
                 models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                   to='transform.transcomplextime')),
                ('country',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristics.country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DefaultRequestExaminationTransform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_diff', relativedeltafield.fields.RelativeDeltaField()),
                ('appl_type',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristics.appltype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
