# Generated by Django 3.2.10 on 2021-12-29 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('characteristics', '0003_auto_20211219_0945'),
        ('transform', '0005_auto_20211219_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryoanum',
            name='appl_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='characteristics.appltype'),
            preserve_default=False,
        ),
    ]
