# Generated by Django 3.2.10 on 2021-12-29 23:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('transform', '0006_countryoanum_appl_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='countryoanum',
            name='CountryOANumCountryUniqueConstraint',
        ),
        migrations.AddConstraint(
            model_name='countryoanum',
            constraint=models.UniqueConstraint(fields=('country', 'appl_type'),
                                               name='CountryOANumCountryApplTypeUniqueConstraint'),
        ),
    ]
