# Generated by Django 3.2.10 on 2021-12-30 04:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('transform', '0007_auto_20211229_2357'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='requestexaminationtransform',
            constraint=models.UniqueConstraint(fields=('country', 'appl_type'),
                                               name='RequestExaminationCountryApplTypeUniqueConstraint'),
        ),
    ]
