# Generated by Django 4.0.1 on 2022-01-20 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('characteristics', '0004_alter_country_isa_countries'),
        ('transform', '0009_rename_final_oa_bool_usoatransform_oa_final_bool'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='allowancetransform',
            name='AllowanceCountryApplTypeUniqueConstraint',
        ),
        migrations.RemoveConstraint(
            model_name='countryoanum',
            name='CountryOANumCountryApplTypeUniqueConstraint',
        ),
        migrations.RemoveConstraint(
            model_name='issuetransform',
            name='IssueCountryApplTypeUniqueConstraint',
        ),
        migrations.RemoveConstraint(
            model_name='publicationtransform',
            name='PublicationCountryApplTypeUniqueConstraint',
        ),
        migrations.RemoveConstraint(
            model_name='requestexaminationtransform',
            name='RequestExaminationCountryApplTypeUniqueConstraint',
        ),
        migrations.RemoveConstraint(
            model_name='usoatransform',
            name='FinalOABoolUniqueConstraint',
        ),
        migrations.AddField(
            model_name='allowancetransform',
            name='prev_appl_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='prev_appl_type_allowance', to='characteristics.appltype'),
        ),
        migrations.AddField(
            model_name='countryoanum',
            name='prev_appl_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='prev_appl_type_oanum', to='characteristics.appltype'),
        ),
        migrations.AddField(
            model_name='issuetransform',
            name='prev_appl_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='prev_appl_type_issuance', to='characteristics.appltype'),
        ),
        migrations.AddField(
            model_name='oatransform',
            name='prev_appl_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='prev_appl_type_oa_transform', to='characteristics.appltype'),
        ),
        migrations.AddField(
            model_name='publicationtransform',
            name='prev_appl_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='prev_appl_type_publication', to='characteristics.appltype'),
        ),
        migrations.AddField(
            model_name='requestexaminationtransform',
            name='prev_appl_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='prev_appl_type_request_examination', to='characteristics.appltype'),
        ),
        migrations.AddConstraint(
            model_name='allowancetransform',
            constraint=models.UniqueConstraint(fields=('country', 'prev_appl_type', 'appl_type'),
                                               name='AllowanceCountryApplTypeUniqueConstraint'),
        ),
        migrations.AddConstraint(
            model_name='countryoanum',
            constraint=models.UniqueConstraint(fields=('country', 'prev_appl_type', 'appl_type'),
                                               name='CountryOANumCountryApplTypeUniqueConstraint'),
        ),
        migrations.AddConstraint(
            model_name='issuetransform',
            constraint=models.UniqueConstraint(fields=('country', 'prev_appl_type', 'appl_type'),
                                               name='IssueCountryApplTypeUniqueConstraint'),
        ),
        migrations.AddConstraint(
            model_name='oatransform',
            constraint=models.UniqueConstraint(fields=('country', 'prev_appl_type', 'appl_type'),
                                               name='OATransformApplTypeUniqueConstraint'),
        ),
        migrations.AddConstraint(
            model_name='publicationtransform',
            constraint=models.UniqueConstraint(fields=('country', 'prev_appl_type', 'appl_type'),
                                               name='PublicationCountryApplTypeUniqueConstraint'),
        ),
        migrations.AddConstraint(
            model_name='requestexaminationtransform',
            constraint=models.UniqueConstraint(fields=('country', 'prev_appl_type', 'appl_type'),
                                               name='RequestExaminationCountryApplTypeUniqueConstraint'),
        ),
        migrations.AddConstraint(
            model_name='usoatransform',
            constraint=models.UniqueConstraint(fields=('oa_final_bool',), name='FinalOABoolUniqueConstraint'),
        ),
    ]
