"""
Django settings for pestimator project.

Generated by 'django-admin startproject' using Django 3.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
import environ
from datetime import timedelta
from pathlib import Path
from .base_settings import *

env = environ.Env(DEBUG=(bool, False))
# env = environ.ENV(
#     DEBUG=(bool, False)
# )

BASE_DIR = Path(__file__).resolve().parent.parent
# Take environment variables from .env file
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

SECRET_KEY = env('SECRET_KEY')

DEBUG = env('DEBUG')

# Build paths inside the project like this: BASE_DIR / 'subdir'.

ALLOWED_HOSTS = ["pestimator.herokuapp.com", "api.estpat.com"]


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DATABASE_NAME'),
        'USER': env('DATABASE_USER'),
        'HOST': env('DATABASE_HOST'),
        'PASSWORD': env('DATABASE_PASSWORD'),
        'PORT': env('DATABASE_PORT')
    }
}

CORS_ALLOWED_ORIGINS = [
    "https://patport.cc",
    "https://www.patport.cc",
    "https://www.estpat.com",
    "https://estpat.com",
]

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

ANYMAIL = {
    "MAILGUN_API_KEY": env("MAILGUN_API_KEY"),
    "MAILGUN_SENDER_DOMAIN": env("MAILGUN_SENDER_DOMAIN"),
}
EMAIL_BACKEND = "anymail.backends.mailgun.EmailBackend"
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL')
SERVER_EMAIL = env('SERVER_EMAIL')

DOMAIN = 'estpat.com'
DOMAIN_FULL = 'https://estpat.com'
SITE_NAME = 'EstPat'

# DOMAIN = 'patport.cc'
# DOMAIN_FULL = 'https://patport.cc'
# SITE_NAME = 'PatPort'

OPEN_EXCHANGE_RATES_APP_ID = env('OPEN_EXCHANGE_RATES_APP_ID')

STRIPE_PRIVATE_KEY = env('STRIPE_PRIVATE_KEY')
GOOGLE_RECAPTCHA_SECRET_KEY = env('GOOGLE_RECAPTCHA_SECRET_KEY')
USE_RECAPTCHA_BOOL = True
MEDIA_ROOT = env('MEDIA_ROOT')
MEDIA_URL = env('MEDIA_URL')
MEDIA_URL_DUPLICATE = env('MEDIA_URL')
