# Generated by Django 3.2.5 on 2021-08-04 06:48

import datetime

import django.db.models.deletion
import relativedeltafield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllowOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_diff', relativedeltafield.fields.RelativeDeltaField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApplOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('date_filing', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FamEstFormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('init_appl_filing_date', models.DateField(default=datetime.date(2020, 1, 1))),
                ('init_appl_indep_claims', models.IntegerField()),
                ('init_appl_claims', models.IntegerField()),
                ('init_appl_drawings', models.IntegerField()),
                ('init_appl_pages', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('method', models.BooleanField(default=False)),
                ('ep_method', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FamOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PublOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_diff', relativedeltafield.fields.RelativeDeltaField()),
                ('appl', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='famform.apploptions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OAOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_diff', relativedeltafield.fields.RelativeDeltaField()),
                ('appl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='famform.apploptions')),
                ('oa_prev', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='famform.oaoptions')),
            ],
        ),
        migrations.CreateModel(
            name='IssueOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_diff', relativedeltafield.fields.RelativeDeltaField()),
                ('appl', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='famform.apploptions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
