# Generated by Django 3.2.9 on 2021-12-15 21:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
import relativedeltafield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characteristics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_diff', relativedeltafield.fields.RelativeDeltaField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApplOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('date_filing', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ApplOptionsParticulars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_examination_early_bool', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CustomApplDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_indep_claims', models.IntegerField(default=None, null=True)),
                ('num_claims', models.IntegerField(default=None, null=True)),
                ('num_claims_multiple_dependent', models.IntegerField(default=None, null=True)),
                ('num_drawings', models.IntegerField(default=None, null=True)),
                ('num_pages_description', models.IntegerField(default=None, null=True)),
                ('num_pages_claims', models.IntegerField(default=None, null=True)),
                ('num_pages_drawings', models.IntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomApplOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_examination_early_bool', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EPCountryCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EPMethodCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FamEstFormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_display_no', models.IntegerField()),
                ('init_appl_filing_date', models.DateField(default=datetime.date(2020, 1, 1))),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('pct_method', models.BooleanField(default=False)),
                ('ep_method', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FamOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PCTApplOptions',
            fields=[
                ('apploptions_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='famform.apploptions')),
            ],
            bases=('famform.apploptions',),
        ),
        migrations.CreateModel(
            name='RequestExaminationOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_diff', relativedeltafield.fields.RelativeDeltaField()),
                ('appl', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='famform.apploptions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PublOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_diff', relativedeltafield.fields.RelativeDeltaField()),
                ('appl', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='famform.apploptions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PCTMethodCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_appl_details',
                 models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                      to='famform.customappldetails')),
                ('custom_appl_options',
                 models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                      to='famform.customapploptions')),
            ],
        ),
        migrations.CreateModel(
            name='PCTCountryCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristics.country')),
                ('custom_appl_details',
                 models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                      to='famform.customappldetails')),
                ('custom_appl_options',
                 models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                      to='famform.customapploptions')),
                ('fam_est_form_data',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='famform.famestformdata')),
            ],
        ),
        migrations.CreateModel(
            name='ParisCountryCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristics.country')),
                ('custom_appl_details',
                 models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                      to='famform.customappldetails')),
                ('custom_appl_options',
                 models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                      to='famform.customapploptions')),
                ('fam_est_form_data',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='famform.famestformdata')),
            ],
        ),
        migrations.CreateModel(
            name='OAOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_diff', relativedeltafield.fields.RelativeDeltaField()),
                ('appl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='famform.apploptions')),
                ('oa_prev',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='famform.oaoptions')),
            ],
        ),
        migrations.CreateModel(
            name='IssueOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_diff', relativedeltafield.fields.RelativeDeltaField()),
                ('appl', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='famform.apploptions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
