# Generated by Django 3.2.9 on 2021-12-15 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0003_initial'),
        ('characteristics', '0001_initial'),
        ('famform', '0001_initial'),
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='famoptions',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family.family'),
        ),
        migrations.AddField(
            model_name='famestformdata',
            name='ep_countries',
            field=models.ManyToManyField(related_name='ep_countries', through='famform.EPCountryCustomization',
                                         to='characteristics.Country'),
        ),
        migrations.AddField(
            model_name='famestformdata',
            name='ep_method_customization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='famform.epmethodcustomization'),
        ),
        migrations.AddField(
            model_name='famestformdata',
            name='family',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='family.family'),
        ),
        migrations.AddField(
            model_name='famestformdata',
            name='init_appl_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='init_country',
                                    to='characteristics.country'),
        ),
        migrations.AddField(
            model_name='famestformdata',
            name='init_appl_details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='application.appldetails'),
        ),
        migrations.AddField(
            model_name='famestformdata',
            name='init_appl_options',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='famform.customapploptions'),
        ),
        migrations.AddField(
            model_name='famestformdata',
            name='init_appl_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristics.appltype'),
        ),
        migrations.AddField(
            model_name='famestformdata',
            name='isa_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='isa_country',
                                    to='characteristics.country'),
        ),
        migrations.AddField(
            model_name='famestformdata',
            name='paris_countries',
            field=models.ManyToManyField(related_name='paris_countries', through='famform.ParisCountryCustomization',
                                         to='characteristics.Country'),
        ),
        migrations.AddField(
            model_name='famestformdata',
            name='pct_countries',
            field=models.ManyToManyField(related_name='pct_countries', through='famform.PCTCountryCustomization',
                                         to='characteristics.Country'),
        ),
        migrations.AddField(
            model_name='famestformdata',
            name='pct_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pct_country',
                                    to='characteristics.country'),
        ),
        migrations.AddField(
            model_name='famestformdata',
            name='pct_method_customization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                       to='famform.pctmethodcustomization'),
        ),
    ]
