# Generated by Django 3.2.5 on 2021-07-25 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characteristics', '0001_initial'),
        ('family', '0001_initial'),
        ('famform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='famoptions',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family.family'),
        ),
        migrations.AddField(
            model_name='famestformdata',
            name='countries',
            field=models.ManyToManyField(to='characteristics.Country'),
        ),
        migrations.AddField(
            model_name='famestformdata',
            name='entity_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristics.entitysize'),
        ),
        migrations.AddField(
            model_name='famestformdata',
            name='family',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='family.family'),
        ),
        migrations.AddField(
            model_name='famestformdata',
            name='init_appl_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='init_country', to='characteristics.country'),
        ),
        migrations.AddField(
            model_name='famestformdata',
            name='init_appl_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristics.appltype'),
        ),
        migrations.AddField(
            model_name='famestformdata',
            name='meth_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meth_country', to='characteristics.country'),
        ),
    ]
