# Generated by Django 3.2.9 on 2021-12-15 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0004_initial'),
        ('famform', '0002_initial'),
        ('characteristics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='famestformdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='epmethodcustomization',
            name='custom_appl_details',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       to='famform.customappldetails'),
        ),
        migrations.AddField(
            model_name='epmethodcustomization',
            name='custom_appl_options',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       to='famform.customapploptions'),
        ),
        migrations.AddField(
            model_name='epcountrycustomization',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristics.country'),
        ),
        migrations.AddField(
            model_name='epcountrycustomization',
            name='custom_appl_details',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       to='famform.customappldetails'),
        ),
        migrations.AddField(
            model_name='epcountrycustomization',
            name='custom_appl_options',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       to='famform.customapploptions'),
        ),
        migrations.AddField(
            model_name='epcountrycustomization',
            name='fam_est_form_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='famform.famestformdata'),
        ),
        migrations.AddField(
            model_name='customapploptions',
            name='doc_format',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='characteristics.docformat'),
        ),
        migrations.AddField(
            model_name='customappldetails',
            name='entity_size',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='characteristics.entitysize'),
        ),
        migrations.AddField(
            model_name='customappldetails',
            name='language',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='characteristics.language'),
        ),
        migrations.AddField(
            model_name='apploptionsparticulars',
            name='doc_format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristics.docformat'),
        ),
        migrations.AddField(
            model_name='apploptions',
            name='appl_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristics.appltype'),
        ),
        migrations.AddField(
            model_name='apploptions',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristics.country'),
        ),
        migrations.AddField(
            model_name='apploptions',
            name='details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.appldetails'),
        ),
        migrations.AddField(
            model_name='apploptions',
            name='fam_options',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='famform.famoptions'),
        ),
        migrations.AddField(
            model_name='apploptions',
            name='particulars',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                       to='famform.apploptionsparticulars'),
        ),
        migrations.AddField(
            model_name='apploptions',
            name='prev_appl_options',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='famform.apploptions'),
        ),
        migrations.AddField(
            model_name='apploptions',
            name='translation_implemented',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE,
                                    to='characteristics.translationimplementedpseudoenum'),
        ),
        migrations.AddField(
            model_name='allowoptions',
            name='appl',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='famform.apploptions'),
        ),
        migrations.AddConstraint(
            model_name='pctcountrycustomization',
            constraint=models.UniqueConstraint(fields=('fam_est_form_data', 'country'),
                                               name='PCTFamEstFormDataCountryUniqueConstraint'),
        ),
        migrations.AddField(
            model_name='pctapploptions',
            name='isa_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristics.country'),
        ),
        migrations.AddConstraint(
            model_name='pariscountrycustomization',
            constraint=models.UniqueConstraint(fields=('fam_est_form_data', 'country'),
                                               name='ParisFamEstFormDataCountryUniqueConstraint'),
        ),
        migrations.AddConstraint(
            model_name='epcountrycustomization',
            constraint=models.UniqueConstraint(fields=('fam_est_form_data', 'country'),
                                               name='EPFamEstFormDataCountryUniqueConstraint'),
        ),
    ]
