# Generated by Django 3.2.3 on 2021-09-15 02:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('famform', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='famestformdata',
            old_name='init_appl_pages',
            new_name='init_appl_pages_desc',
        ),
        migrations.AddField(
            model_name='famestformdata',
            name='init_appl_pages_claims',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='famestformdata',
            name='init_appl_pages_drawings',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
