# Generated by Django 4.0.1 on 2022-01-19 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('characteristics', '0004_alter_country_isa_countries'),
        ('famform', '0004_famestformdata_isa_entity_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pctapploptions',
            name='isa_entity_size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='characteristics.entitysize'),
        ),
    ]
