# Generated by Django 3.2.3 on 2021-10-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('famform', '0004_auto_20210915_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='apploptions',
            name='translation_full_required',
            field=models.BooleanField(default=False),
        ),
    ]
