# Generated by Django 4.0.1 on 2022-01-20 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('famform', '0005_alter_pctapploptions_isa_entity_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='USOAOptions',
            fields=[
                ('oaoptions_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='famform.oaoptions')),
                ('oa_final_bool', models.BooleanField(default=False)),
            ],
            bases=('famform.oaoptions',),
        ),
    ]
