# Generated by Django 3.2.3 on 2021-10-23 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('characteristics', '0008_country_ep_validation_translation_required'),
        ('famform', '0008_auto_20211010_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomApplDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_indep_claims', models.IntegerField()),
                ('num_claims', models.IntegerField()),
                ('num_drawings', models.IntegerField()),
                ('num_pages_description', models.IntegerField()),
                ('num_pages_claims', models.IntegerField()),
                ('num_pages_drawings', models.IntegerField()),
                ('entity_size',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristics.entitysize')),
                ('language',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristics.languages')),
            ],
        ),
        migrations.CreateModel(
            name='PCTCountryCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristics.country')),
                ('custom_appl_details',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='famform.customappldetails')),
                ('fam_est_form_data',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='famform.famestformdata')),
            ],
        ),
        migrations.CreateModel(
            name='ParisCountryCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristics.country')),
                ('custom_appl_details',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='famform.customappldetails')),
                ('fam_est_form_data',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='famform.famestformdata')),
            ],
        ),
        migrations.CreateModel(
            name='EPCountryCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristics.country')),
                ('custom_appl_details',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='famform.customappldetails')),
                ('fam_est_form_data',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='famform.famestformdata')),
            ],
        ),
        migrations.AddConstraint(
            model_name='pctcountrycustomization',
            constraint=models.UniqueConstraint(fields=('fam_est_form_data', 'country'),
                                               name='PCTFamEstFormDataCountryUniqueConstraint'),
        ),
        migrations.AddConstraint(
            model_name='pariscountrycustomization',
            constraint=models.UniqueConstraint(fields=('fam_est_form_data', 'country'),
                                               name='ParisFamEstFormDataCountryUniqueConstraint'),
        ),
        migrations.AddConstraint(
            model_name='epcountrycustomization',
            constraint=models.UniqueConstraint(fields=('fam_est_form_data', 'country'),
                                               name='EPFamEstFormDataCountryUniqueConstraint'),
        ),
    ]
