# Generated by Django 3.2.3 on 2021-10-23 02:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('characteristics', '0008_country_ep_validation_translation_required'),
        ('famform', '0010_auto_20211023_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='famestformdata',
            name='ep_countries2',
            field=models.ManyToManyField(related_name='ep_countries2', through='famform.EPCountryCustomization',
                                         to='characteristics.Country'),
        ),
        migrations.AddField(
            model_name='famestformdata',
            name='paris_countries2',
            field=models.ManyToManyField(related_name='paris_countries2', through='famform.ParisCountryCustomization',
                                         to='characteristics.Country'),
        ),
        migrations.AddField(
            model_name='famestformdata',
            name='pct_countries2',
            field=models.ManyToManyField(related_name='pct_countries2', through='famform.PCTCountryCustomization',
                                         to='characteristics.Country'),
        ),
    ]
