# Generated by Django 3.2.3 on 2021-10-23 02:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('famform', '0011_auto_20211023_0257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='famestformdata',
            name='ep_countries',
        ),
        migrations.RemoveField(
            model_name='famestformdata',
            name='paris_countries',
        ),
        migrations.RemoveField(
            model_name='famestformdata',
            name='pct_countries',
        ),
    ]
