# Generated by Django 3.2.3 on 2021-10-23 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('characteristics', '0008_country_ep_validation_translation_required'),
        ('famform', '0014_auto_20211023_0332'),
    ]

    operations = [
        migrations.CreateModel(
            name='EPCountryCustomization2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristics.country')),
                ('custom_appl_details',
                 models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                      to='famform.customappldetails')),
                ('fam_est_form_data',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='famform.famestformdata')),
            ],
        ),
        migrations.AddConstraint(
            model_name='epcountrycustomization2',
            constraint=models.UniqueConstraint(fields=('fam_est_form_data', 'country'),
                                               name='EPFamEstFormDataCountryUniqueConstraint2'),
        ),
    ]
