# Generated by Django 3.2.3 on 2021-10-23 04:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('characteristics', '0008_country_ep_validation_translation_required'),
        ('famform', '0016_auto_20211023_0412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pariscountrycustomization',
            name='country',
        ),
        migrations.RemoveField(
            model_name='pariscountrycustomization',
            name='custom_appl_details',
        ),
        migrations.RemoveField(
            model_name='pariscountrycustomization',
            name='fam_est_form_data',
        ),
        migrations.RemoveField(
            model_name='pctcountrycustomization',
            name='country',
        ),
        migrations.RemoveField(
            model_name='pctcountrycustomization',
            name='custom_appl_details',
        ),
        migrations.RemoveField(
            model_name='pctcountrycustomization',
            name='fam_est_form_data',
        ),
        migrations.AlterField(
            model_name='famestformdata',
            name='ep_countries',
            field=models.ManyToManyField(related_name='ep_countries', through='famform.EPCountryCustomization2',
                                         to='characteristics.Country'),
        ),
        migrations.AlterField(
            model_name='famestformdata',
            name='paris_countries',
            field=models.ManyToManyField(related_name='paris_countries', through='famform.ParisCountryCustomization2',
                                         to='characteristics.Country'),
        ),
        migrations.AlterField(
            model_name='famestformdata',
            name='pct_countries',
            field=models.ManyToManyField(related_name='pct_countries', through='famform.PCTCountryCustomization2',
                                         to='characteristics.Country'),
        ),
        migrations.DeleteModel(
            name='EPCountryCustomization',
        ),
        migrations.DeleteModel(
            name='ParisCountryCustomization',
        ),
        migrations.DeleteModel(
            name='PCTCountryCustomization',
        ),
    ]
