# Generated by Django 3.2.3 on 2021-10-23 04:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('characteristics', '0008_country_ep_validation_translation_required'),
        ('famform', '0017_auto_20211023_0415'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EPCountryCustomization2',
            new_name='EPCountryCustomization',
        ),
        migrations.RenameModel(
            old_name='ParisCountryCustomization2',
            new_name='ParisCountryCustomization',
        ),
        migrations.RenameModel(
            old_name='PCTCountryCustomization2',
            new_name='PCTCountryCustomization',
        ),
        migrations.RemoveConstraint(
            model_name='epcountrycustomization',
            name='EPFamEstFormDataCountryUniqueConstraint2',
        ),
        migrations.RemoveConstraint(
            model_name='pariscountrycustomization',
            name='ParisFamEstFormDataCountryUniqueConstraint2',
        ),
        migrations.RemoveConstraint(
            model_name='pctcountrycustomization',
            name='PCTFamEstFormDataCountryUniqueConstraint2',
        ),
        migrations.AddConstraint(
            model_name='epcountrycustomization',
            constraint=models.UniqueConstraint(fields=('fam_est_form_data', 'country'),
                                               name='EPFamEstFormDataCountryUniqueConstraint'),
        ),
        migrations.AddConstraint(
            model_name='pariscountrycustomization',
            constraint=models.UniqueConstraint(fields=('fam_est_form_data', 'country'),
                                               name='ParisFamEstFormDataCountryUniqueConstraint'),
        ),
        migrations.AddConstraint(
            model_name='pctcountrycustomization',
            constraint=models.UniqueConstraint(fields=('fam_est_form_data', 'country'),
                                               name='PCTFamEstFormDataCountryUniqueConstraint'),
        ),
    ]
