# Generated by Django 3.2.3 on 2021-10-23 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('characteristics', '0008_country_ep_validation_translation_required'),
        ('famform', '0018_auto_20211023_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pariscountrycustomization',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='characteristics.country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pariscountrycustomization',
            name='custom_appl_details',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       to='famform.customappldetails'),
        ),
    ]
