# Generated by Django 3.2.3 on 2021-10-23 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('characteristics', '0008_country_ep_validation_translation_required'),
        ('famform', '0019_auto_20211023_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customappldetails',
            name='entity_size',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='characteristics.entitysize'),
        ),
        migrations.AlterField(
            model_name='customappldetails',
            name='language',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='characteristics.languages'),
        ),
        migrations.AlterField(
            model_name='customappldetails',
            name='num_claims',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='customappldetails',
            name='num_drawings',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='customappldetails',
            name='num_indep_claims',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='customappldetails',
            name='num_pages_claims',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='customappldetails',
            name='num_pages_description',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='customappldetails',
            name='num_pages_drawings',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
