# Generated by Django 3.2.3 on 2021-10-23 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('famform', '0020_auto_20211023_0953'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='PCTMethodCustomization',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('custom_appl_details', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='famform.customappldetails')),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='EPMethodCustomization',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('custom_appl_details', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='famform.customappldetails')),
        #     ],
        # ),
        # migrations.AddField(
        #     model_name='famestformdata',
        #     name='ep_method_customization',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='famform.epmethodcustomization'),
        # ),
        # migrations.AddField(
        #     model_name='famestformdata',
        #     name='pct_method_customization',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='famform.pctmethodcustomization'),
        # ),
        # migrations.AddConstraint(
        #     model_name='pctmethodcustomization',
        #     constraint=models.UniqueConstraint(fields=('fam_est_form_data',), name='pctCustomization'),
        # ),
        # migrations.AddConstraint(
        #     model_name='epmethodcustomization',
        #     constraint=models.UniqueConstraint(fields=('fam_est_form_data',), name='epCustomization'),
        # ),
    ]
