# Generated by Django 3.2.3 on 2021-10-23 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('famform', '0021_auto_20211023_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='PCTMethodCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_appl_details',
                 models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                      to='famform.customappldetails')),
            ],
        ),
        migrations.CreateModel(
            name='EPMethodCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_appl_details',
                 models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                      to='famform.customappldetails')),
            ],
        ),
        migrations.AddField(
            model_name='famestformdata',
            name='ep_method_customization',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE,
                                       to='famform.epmethodcustomization'),
        ),
        migrations.AddField(
            model_name='famestformdata',
            name='pct_method_customization',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE,
                                       to='famform.pctmethodcustomization'),
        ),
    ]
