# Generated by Django 3.2.3 on 2021-10-31 07:27

from django.db import migrations, models
import django.db.models.deletion


# from application.models import ApplDetails
# from famform.models import FamEstFormData


def set_defaults(apps, schema_editor):
    FamEstFormData = apps.get_model("famform", "FamEstFormData")
    for x in FamEstFormData.objects.all().iterator():
        ApplDetails = apps.get_model("application", "ApplDetails")
        # ApplDetails.objects.all()
        EntitySize = apps.get_model("characteristics", "EntitySize")
        entity_size = EntitySize.objects.first()
        Languages = apps.get_model("characteristics", "Languages")
        language = Languages.objects.first()
        applDetails = ApplDetails.objects.create(
            num_indep_claims=1,
            num_claims=1,
            num_drawings=1,
            num_pages_description=1,
            num_pages_claims=1,
            num_pages_drawings=1,
            entity_size=entity_size,
            language=language)
        # applDetails.save()
        x.init_appl_details = applDetails
        x.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('application', '0012_alter_appldetails_entity_size'),
        ('famform', '0023_auto_20211031_0720'),
    ]

    operations = [
        migrations.RunPython(set_defaults, reverse_func),
        # migrations.AlterField(
        #     model_name='famestformdata',
        #     name='init_appl_details',
        #     field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='application.appldetails'),
        # ),
    ]
