# Generated by Django 3.2.3 on 2021-10-31 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('application', '0012_alter_appldetails_entity_size'),
        ('famform', '0024_alter_famestformdata_init_appl_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='famestformdata',
            name='init_appl_details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='application.appldetails'),
        ),
    ]
