# Generated by Django 3.2.3 on 2021-11-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('famform', '0025_alter_famestformdata_init_appl_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='customappldetails',
            name='num_claims_multiple_dependent',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
