# Generated by Django 3.2.3 on 2021-11-22 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('famform', '0026_customappldetails_num_claims_multiple_dependent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomApplOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_examination_early_bool', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='epcountrycustomization',
            name='custom_appl_options',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       to='famform.customapploptions'),
        ),
        migrations.AddField(
            model_name='epmethodcustomization',
            name='custom_appl_options',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       to='famform.customapploptions'),
        ),
        migrations.AddField(
            model_name='famestformdata',
            name='init_appl_options',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       to='famform.customapploptions'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pariscountrycustomization',
            name='custom_appl_options',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       to='famform.customapploptions'),
        ),
        migrations.AddField(
            model_name='pctcountrycustomization',
            name='custom_appl_options',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       to='famform.customapploptions'),
        ),
        migrations.AddField(
            model_name='pctmethodcustomization',
            name='custom_appl_options',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       to='famform.customapploptions'),
        ),
    ]
