# Generated by Django 3.2.3 on 2021-11-22 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('famform', '0028_alter_famest_formdata_init_appl_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='famestformdata',
            name='init_appl_options',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='famform.customapploptions'),
        ),
    ]
