# Generated by Django 3.2.3 on 2021-11-24 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('characteristics', '0011_docformat'),
        ('famform', '0030_requestexaminationoptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='customapploptions',
            name='doc_format',
            field=models.ForeignKey(null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='characteristics.docformat'),
        ),
    ]
