# Generated by Django 3.2.3 on 2021-11-24 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('characteristics', '0011_1_docformat_run_python'),
        ('famform', '0031_customapploptions_doc_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='apploptions',
            name='custom_appl_options',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='famform.customapploptions'),
        ),
        migrations.AlterField(
            model_name='customapploptions',
            name='doc_format',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='characteristics.docformat'),
            preserve_default=False,
        ),
    ]
