# Generated by Django 3.2.3 on 2021-11-24 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('famform', '0033_customapploptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apploptions',
            name='custom_appl_options',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='famform.customapploptions'),
        ),
    ]
