# Generated by Django 3.2.3 on 2021-11-29 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('characteristics', '0016_auto_20211129_1739'),
        ('famform', '0034_alter_apploptions_custom_appl_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customappldetails',
            name='language',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='characteristics.language'),
        ),
    ]
