# Generated by Django 3.2.3 on 2021-11-30 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('characteristics', '0019_auto_20211129_1749'),
        ('famform', '0035_alter_customappldetails_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customapploptions',
            name='doc_format',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='characteristics.docformat'),
        ),
    ]
