# Generated by Django 3.2.3 on 2021-11-30 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('characteristics', '0019_auto_20211129_1749'),
        ('famform', '0036_alter_customapploptions_doc_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apploptions',
            name='custom_appl_options',
        ),
        migrations.CreateModel(
            name='ApplOptionsParticulars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_examination_early_bool', models.BooleanField(default=False)),
                ('doc_format',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristics.docformat')),
            ],
        ),
    ]
