# Generated by Django 3.2.3 on 2021-11-30 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('famform', '0038_run_python_particulars'),
    ]

    operations = [
        migrations.AddField(
            model_name='apploptions',
            name='particulars',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE,
                                       to='famform.apploptionsparticulars'),
        ),
    ]
