# Generated by Django 3.2.3 on 2021-11-30 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('famform', '0040_apploptions_particulars_adding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apploptions',
            name='particulars',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                       to='famform.apploptionsparticulars'),
        ),
    ]
