# Generated by Django 3.2.3 on 2021-12-01 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('famform', '0042_method_customization_one_to_one'),
    ]

    operations = [
        migrations.AlterField(
            model_name='famestformdata',
            name='ep_method_customization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='famform.epmethodcustomization'),
        ),
        migrations.AlterField(
            model_name='famestformdata',
            name='pct_method_customization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                       to='famform.pctmethodcustomization'),
        ),
    ]
