# Generated by Django 3.2.3 on 2021-12-02 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('characteristics', '0021_translationimplementedpseudoenum'),
        ('famform', '0043_auto_20211201_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='apploptions',
            name='translation_implemented',
            field=models.ForeignKey(default=2,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='characteristics.translationimplementedpseudoenum'),
        ),
    ]
