# Generated by Django 3.2.3 on 2021-09-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_data',
            field=models.BooleanField(default=False),
        ),
    ]
