# Generated by Django 3.2.3 on 2021-10-02 06:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0002_user_admin_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='terms_agreed',
            field=models.BooleanField(default=False),
        ),
    ]
