# Generated by Django 3.2.3 on 2021-10-04 04:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0003_user_terms_agreed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recaptcha',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
