# Generated by Django 3.2.3 on 2021-10-04 04:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0004_user_recaptcha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='recaptcha',
            field=models.CharField(default='', max_length=200),
        ),
    ]
